name: Rule backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rules branch
        uses: actions/checkout@v4
        with:
          ref: rules

      - name: Download and rename geosite rules
        run: |
          mkdir -p singbox/geosite
          for url in $(curl -s https://api.github.com/repos/lyc8503/sing-box-rules/contents/rule-set-geosite | jq -r '.[].download_url'); do
            filename=$(basename "$url")
            new_filename="${filename#geosite-}"
            curl -L "$url" -o "singbox/geosite/$new_filename"
          done

      - name: Download original rules
        run: |
          mkdir -p singbox Mihomo
          curl -L https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules-singbox.srs -o singbox/ad.srs
          curl -L https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules-mihomo.mrs -o Mihomo/ad.mrs

      - name: Check for changes
        run: |
          git diff --exit-code singbox/geosite/ singbox/ad.srs Mihomo/ad.mrs
        continue-on-error: true

      - name: Commit and push changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add singbox/geosite/ singbox/ad.srs Mihomo/ad.mrs
          git commit --allow-empty -m "Update ad and geosite rules"
          git push origin rules
